listener 1883
allow_anonymous true
persistence false
log_dest stdout

connection chevron1-taurus
address stargate-taurus:1883
topic # both 2 pocket/taurus/ ""
try_private true
keepalive_interval 20
restart_timeout 5 15
notifications false

connection chevron7-earth
address mqtt:1883
topic # out 2 "" pocket/
try_private true
keepalive_interval 40
restart_timeout 30 50
